FROM mcr.microsoft.com/dotnet/core/sdk:3.1-bionic-arm32v7 as basebuild

WORKDIR /bench

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o .

#runtime
FROM mcr.microsoft.com/dotnet/core/runtime:3.1-bionic-arm32v7 as runtime
WORKDIR /bench
COPY --from=basebuild /bench .

ENTRYPOINT ["./benchtool-dotnetcore"]
